version: '3'
services:
  nodejs:
    # image: nhatsang25/backup-nodejs:latest
    build: ./library_server
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - flask
    networks:
      - web  

  flask:
    # image: nhatsang25/backup-flask:v2
    build: ./library_recommendation
    ports:
      - "3001:3001"
    environment:
      - FLASK_APP=run.py
    networks:
      - web 

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - web  

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #   depends_on:
  #     - flask
  #     - nodejs
  #   networks:
  #     - web  

networks:
  web:
    external: false  
